/** @type {import('tailwindcss').Config} */
import { sizes } from "./sizes";

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontFamily: {
      sans: [
        "Public Sans Web",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica",
        "Arial",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
      ],
    },
    screens: {
      card: "160px",
      cardLg: "240px",
      mobile: "320px",
      mobileMd: "375px",
      mobileLg: "480px",
      tablet: "640px",
      tabletMd: "768px",
      tabletLg: "880px",
      tabletXl: "992px",
      desktop: "1024px",
      desktopLg: "1200px",
      desktopMd: "1080px",
      desktopXl: "1300px",
      widescreen: "1400px",
    },
    extend: {
      colors: {
        baseCool: "#f9f9f9",
        baseLightest: "#f0f0f0",
        baseLighter: "#e6e6e6",
        baseLight: "#adadad",
        baseExtraLight: "#f6f6f6",
        base: "#757575",
        baseDark: "#5c5c5c",
        baseDarker: "#454545",
        baseDarkest: "#1b1b1b",
        ink: "#1b1b1b",
        primary: "#005ea2",
        primaryVivid: "#0050d8",
        primaryLight: "#73b3e7",
        primaryLighter: "#d9e8f6",
        primaryExtraLight: "#eff6fb",
        primaryDark: "#1a4480",
        primaryDarker: "#162e51",
        secondary: "#008817",
        secondaryLight: "#b4d0b9",
        secondaryLighter: "#dbebde",
        secondaryExtraLight: "#f6f9f6",
        secondaryVivid: "#216e1f",
        secondaryDark: "#154c21",
        secondaryDarker: "#19311e",
        tertiary: "#676cc8",
        tertiaryLight: "#a5a8eb",
        tertiaryLighter: "#edf0ff",
        tertiaryExtraLight: "#f8f8ff",
        tertiaryVivid: "#656bd7",
        tertiaryDark: "#4a50c4",
        tertiaryDarker: "#3333a3",
        accentCool: "#00bde3",
        accentCoolLight: "#97d4ea",
        accentCoolLighter: "#c3ebfa",
        accentCoolExtraLight: "#f0f9fc",
        accentCoolDark: "#28a0cb",
        accentCoolDarker: "#07648d",
        accentWarm: "#fa9441",
        accentWarmLight: "#ffbc78",
        accentWarmLighter: "#f2e4d4",
        accentWarmExtraLight: "#fef2e4",
        accentWarmDark: "#c05600",
        accentWarmDarker: "#775540",

        infoLighter: "#e7f6f8",
        infoLight: "#99deea",
        info: "#00bde3",
        infoDark: "#009ec1",
        infoDarker: "#2e6276",
        errorLighter: "#f4e3db",
        errorLight: "#f39268",
        error: "#d54309",
        errorDark: "#b50909",
        errorDarker: "#6f3331",
        warningLighter: "#faf3d1",
        warningLight: "#fee685",
        warning: "#ffbe2e",
        warningDark: "#e5a000",
        warningDarker: "#936f38",
        successLighter: "#ecf3ec",
        successLight: "#70e17b",
        success: "#00a91c",
        successDark: "#008817",
        successDarker: "#216e1f",
        disabledLight: "#e6e6e6",
        disabled: "#c9c9c9",
        disabledDark: "#adadad",
        emergency: "#9c3d10",
        emergencyDark: "#332d29",

        njBlack: "#363636",
        white: "#ffffff",
        black: "#000000",
      },
      width: sizes,
      height: sizes,
      minWidth: sizes,
      minHeight: sizes,
      maxWidth: sizes,
      maxHeight: sizes,
      padding: sizes,
      margin: sizes,
      inset: sizes,
      fontSize: sizes,
      borderRadius: {
        radius5: "5px",
        radius10: "10px",
        radius15: "15px",
        radius20: "20px",
        radius25: "25px",
        radius30: "30px",
        radius35: "35px",
        radius40: "40px",
        radius45: "45px",
        radius50: "50px",
      },
      borderWidth: sizes,
      boxShadow: {
        shadow1: "0 1px 4px 0 rgba(0, 0, 0, 0.1)",
        shadow2: "0 4px 8px 0 rgba(0, 0, 0, 0.1)",
        shadow3: "0 8px 16px 0 rgba(0, 0, 0, 0.1)",
        shadow4: "0 12px 24px 0 rgba(0, 0, 0, 0.1)",
        shadow5: "0 16px 32px 0 rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
