import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        baseCool: "#f9f9f9",
        baseLightest: "#f0f0f0",
        baseLighter: "#e6e6e6",
        baseLight: "#adadad",
        baseExtraLight: "#f6f6f6",
        base: "#757575",
        baseDark: "#5c5c5c",
        baseDarker: "#454545",
        baseDarkest: "#1b1b1b",
        ink: "#1b1b1b",
        primary: "#005ea2",
        primaryVivid: "#0050d8",
        primaryLight: "#",
        primaryLighter: "#",
        primaryExtraLight: "#",
        primaryDark: "#",
        primaryDarker: "#",
        secondary: "#",
        secondaryLight: "#",
        secondaryLighter: "#",
        secondaryExtraLight: "#",
        secondaryVivid: "#",
        secondaryDark: "#",
        secondaryDarker: "#",
        tertiary: "#",
        tertiaryLight: "#",
        tertiaryLighter: "#",
        tertiaryExtraLight: "#",
        tertiaryVivid: "#",
        tertiaryDark: "#",
        tertiaryDarker: "#",
        accentCool: "#",
        accentCoolLight: "#",
        accentCoolLighter: "#",
        accentCoolExtraLight: "#",
        accentCoolDark: "#",
        accentCoolDarker: "#",
        accentWarm: "#",
        accentWarmLight: "#",
        accentWarmLighter: "#",
        accentWarmExtraLight: "#",
        accentWarmDark: "#",
        accentWarmDarker: "#",
        infoLighter: "#",
        infoLight: "#",
        info: "#",
        infoDark: "#",
        infoDarker: "#",
        errorLighter: "#",
        errorLight: "#",
        error: "#",
        errorDark: "#",
        errorDarker: "#",
        warningLighter: "#",
        warningLight: "#",
        warning: "#",
        warningDark: "#",
        warningDarker: "#",
        successLighter: "#",
        successLight: "#",
        success: "#",
        successDark: "#",
        successDarker: "#",
        disabledLight: "#",
        disabled: "#",
        disabledDark: "#",
        emergency: "#",
        emergencyDark: "#",
        njBlack: "#",
        white: "#",
        black: "#",
      },
    },
  },
  plugins: [],
} satisfies Config;
