"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const express_1 = tslib_1.__importDefault(require("express"));
const homePage_1 = require("../../queries/homePage");
const routeHandler_1 = require("../../routeHandler");
const industriesSubRouter = express_1.default.Router({ mergeParams: true });
industriesSubRouter.get('/considerations', (0, routeHandler_1.routeHandler)(homePage_1.HOMEPAGE_QUERY));
industriesSubRouter.get('/hot-spots', (0, routeHandler_1.routeHandler)(homePage_1.HOMEPAGE_QUERY));
industriesSubRouter.get('/top-sectors', (0, routeHandler_1.routeHandler)(homePage_1.HOMEPAGE_QUERY));
industriesSubRouter.get('/career-maps', (0, routeHandler_1.routeHandler)(homePage_1.HOMEPAGE_QUERY));
exports.default = industriesSubRouter;
