CREATE TABLE IF NOT EXISTS blsoccupationhandbook(
  current_year integer,
  current_year_agg integer,
  last_updated character varying(16),
  occupation_id integer,
  occupation_citation text,
  occupation_description_type character varying(8),
  occupation_description text,
  occupation_how_to_become_one_section_body_type character varying(8),
  occupation_how_to_become_one_section_body text,
  occupation_how_to_become_one_section_image_type character varying(8),
  occupation_how_to_become_one_section_image text,
  occupation_how_to_become_one_section_title_type character varying(8),
  occupation_how_to_become_one_section_title text,
  occupation_image_type character varying(8),
  occupation_image text,
  occupation_job_outlook_section_body_type character varying(8),
  occupation_job_outlook_section_body text,
  occupation_job_outlook_section_chart_type character varying(8),
  occupation_job_outlook_section_chart text,
  occupation_job_outlook_section_datatable_type character varying(8),
  occupation_job_outlook_section_datatable text,
  occupation_job_outlook_section_title_type character varying(8),
  occupation_job_outlook_section_title text,
  occupation_more_information_section_body_type character varying(8),
  occupation_more_information_section_body text,
  occupation_more_information_section_title_type character varying(8),
  occupation_more_information_section_title text,
  occupation_occupation_code character varying(8),
  occupation_occupation_name_full_type character varying(8),
  occupation_occupation_name_full text,
  occupation_occupation_name_short_plural_type character varying(8),
  occupation_occupation_name_short_plural text,
  occupation_occupation_name_short_singular_type character varying(8),
  occupation_occupation_name_short_singular text,
  occupation_pay_section_body_type character varying(8),
  occupation_pay_section_body text,
  occupation_pay_section_chart_html_type character varying(8),
  occupation_pay_section_chart_html text,
  occupation_pay_section_title_type character varying(8),
  occupation_pay_section_title text,
  occupation_publish_date_format character varying(16),
  occupation_publish_date_type character varying(8),
  occupation_publish_date character varying(16),
  occupation_publish_time_format character varying(16),
  occupation_publish_time_note text,
  occupation_publish_time_type character varying(8),
  occupation_publish_time character varying(8),
  occupation_quick_facts_qf_employment_openings_help_type character varying(8),
  occupation_quick_facts_qf_employment_openings_help text,
  occupation_quick_facts_qf_employment_openings_value_type character varying(8),
  occupation_quick_facts_qf_employment_openings_value integer,
  occupation_quick_facts_qf_employment_openings_value_agg integer,
  occupation_quick_facts_qf_employment_outlook_description text,
  occupation_quick_facts_qf_employment_outlook_help_type character varying(8),
  occupation_quick_facts_qf_employment_outlook_help text,
  occupation_quick_facts_qf_employment_outlook_range_type character varying(8),
  occupation_quick_facts_qf_employment_outlook_range text,
  occupation_quick_facts_qf_employment_outlook_value_type character varying(8),
  occupation_quick_facts_qf_employment_outlook_value integer,
  occupation_quick_facts_qf_employment_outlook_value_agg integer,
  occupation_quick_facts_qf_entry_level_education_help_type character varying(8),
  occupation_quick_facts_qf_entry_level_education_help text,
  occupation_quick_facts_qf_entry_level_education_value_type character varying(8),
  occupation_quick_facts_qf_entry_level_education_value text,
  occupation_quick_facts_qf_median_pay_annual_help_type character varying(8),
  occupation_quick_facts_qf_median_pay_annual_help text,
  occupation_quick_facts_qf_median_pay_annual_note_type character varying(8),
  occupation_quick_facts_qf_median_pay_annual_note text,
  occupation_quick_facts_qf_median_pay_annual_range_type character varying(8),
  occupation_quick_facts_qf_median_pay_annual_range text,
  occupation_quick_facts_qf_median_pay_annual_value_type character varying(8),
  occupation_quick_facts_qf_median_pay_annual_value integer,
  occupation_quick_facts_qf_median_pay_annual_value_agg integer,
  occupation_quick_facts_qf_median_pay_hourly_help_type character varying(8),
  occupation_quick_facts_qf_median_pay_hourly_help text,
  occupation_quick_facts_qf_median_pay_hourly_note_type character varying(8),
  occupation_quick_facts_qf_median_pay_hourly_note text,
  occupation_quick_facts_qf_median_pay_hourly_value_type character varying(8),
  occupation_quick_facts_qf_median_pay_hourly_value decimal,
  occupation_quick_facts_qf_median_pay_hourly_value_agg decimal,
  occupation_quick_facts_qf_number_of_jobs_help_type character varying(8),
  occupation_quick_facts_qf_number_of_jobs_help text,
  occupation_quick_facts_qf_number_of_jobs_range_type character varying(8),
  occupation_quick_facts_qf_number_of_jobs_range text,
  occupation_quick_facts_qf_number_of_jobs_value_type character varying(8),
  occupation_quick_facts_qf_number_of_jobs_value integer,
  occupation_quick_facts_qf_number_of_jobs_value_agg integer,
  occupation_quick_facts_qf_on_the_job_training_help_type character varying(8),
  occupation_quick_facts_qf_on_the_job_training_help text,
  occupation_quick_facts_qf_on_the_job_training_value_type character varying(8),
  occupation_quick_facts_qf_on_the_job_training_value text,
  occupation_quick_facts_qf_work_experience_help_type character varying(8),
  occupation_quick_facts_qf_work_experience_help text,
  occupation_quick_facts_qf_work_experience_value_type character varying(8),
  occupation_quick_facts_qf_work_experience_value text,
  occupation_similar_occupations_section_body_type character varying(8),
  occupation_similar_occupations_section_body text,
  occupation_similar_occupations_section_title_type character varying(8),
  occupation_similar_occupations_section_title text,
  occupation_soc_coverage_soc_code_type character varying(8),
  occupation_soc_coverage_soc_code  character varying(16),
  occupation_state_and_area_section_body_type character varying(8),
  occupation_state_and_area_section_body text,
  occupation_state_and_area_section_title_type character varying(8),
  occupation_state_and_area_section_title text,
  occupation_summary_how_to_become_one_type character varying(8),
  occupation_summary_how_to_become_one text,
  occupation_summary_more_information_type character varying(8),
  occupation_summary_more_information text,
  occupation_summary_outlook_type character varying(8),
  occupation_summary_outlook text,
  occupation_summary_pay_type character varying(8),
  occupation_summary_pay text,
  occupation_summary_similar_occupations_type character varying(8),
  occupation_summary_similar_occupations text,
  occupation_summary_state_and_area_type character varying(8),
  occupation_summary_state_and_area text,
  occupation_summary_what_they_do_type character varying(8),
  occupation_summary_what_they_do text,
  occupation_summary_work_environment_type character varying(8),
  occupation_summary_work_environment text,
  occupation_title_type character varying(8),
  occupation_title text,
  occupation_video_link text,
  occupation_what_they_do_section_body_type character varying(8),
  occupation_what_they_do_section_body text,
  occupation_what_they_do_section_image_type character varying(8),
  occupation_what_they_do_section_image text,
  occupation_what_they_do_section_title_type character varying(8),
  occupation_what_they_do_section_title text,
  occupation_work_environment_section_body_type character varying(8),
  occupation_work_environment_section_body text,
  occupation_work_environment_section_image_type character varying(8),
  occupation_work_environment_section_image text,
  occupation_work_environment_section_title_type character varying(8),
  occupation_work_environment_section_title text,
  projection_year integer,
  projection_year_agg integer,
  publication_title text,
  reference_period text,
  reference_year integer,
  reference_year_agg integer
);
