CREATE TABLE IF NOT EXISTS providers
(
    PROVIDERID character varying(16) NOT NULL PRIMARY KEY,
    NAME character varying(256),
    SCHOOLIDENTIFICATIONNUMBER character varying(64),
    STREET1 character varying(128),
    STREET2 character varying(128),
    CITY character varying(64),
    STATE character varying(8),
    ZIP character varying(16),
    COUNTY character varying(32),
    MSTREET1 character varying(128),
    MSTREET2 character varying(128),
    MCITY character varying(64),
    MSTATE character varying(8),
    MZIP character varying(16),
    CONTACTFIRSTNAME character varying(128),
    CONTACTLASTNAME character varying(128),
    CONTACTTITLE character varying(128),
    PHONE character varying(16),
    PHONEEXTENSION character varying(8),
    FAX character varying(16),
    WEBSITE character varying(256),
    EMAIL character varying(256),
    LICENSINGAGENCYID character varying(16),
    TYPEID character varying(16),
    NONGOVAPPROVAL character varying(128),
    CERTAPPROVALEXP timestamp,
    CUSTOMIZED character varying(8),
    DISTANCELEARNING character varying(8),
    SPEAKSPANISH character varying(8),
    OTHERLANGUAGES character varying(8),
    LANGUAGES character varying(256),
    CAREERASSIST character varying(8),
    ONESTOPCAREER character varying(8),
    PERSONALASSIST character varying(8),
    ACCESSAJBATB character varying(8),
    CHILDCARE character varying(8),
    ASSISTOBTAININGCHILDCARE character varying(8),
    EVENINGCOURSES character varying(8),
    ACCESSFORDISABLED character varying(8),
    BUSROUTE1 character varying(256),
    BUSROUTE2 character varying(256),
    TRNROUTE1 character varying(256),
    TRNROUTE2 character varying(256),
    WIBCOMMENT text,
    STATECOMMENT text,
    DTSUBMITTED timestamp,
    STATUSNAME character varying(64)
);