CREATE TABLE etpl AS SELECT
    programs.PROVIDERID,
    programs.OFFICIALNAME,
    programs.CIPCODE,
    programs.APPROVINGAGENCYID,
    programs.OTHERAGENCY,
    programs.SUBMITTEDTOWIB,
    programs.TUITION,
    programs.FEES,
    programs.BOOKSMATERIALSCOST,
    programs.SUPPLIESTOOLSCOST,
    programs.OTHERCOSTS,
    programs.TOTALCOST,
    programs.PREREQUISITES,
    programs.WIAELIGIBLE,
    programs.LEADTODEGREE,
    programs.DEGREEAWARDED,
    programs.LEADTOLICENSE,
    programs.LICENSEAWARDED,
    programs.LEADTOINDUSTRYCREDENTIAL,
    programs.INDUSTRYCREDENTIAL,
    programs.FINANCIALAID,
    programs.DESCRIPTION,
    programs.CREDIT,
    programs.TOTALCLOCKHOURS,
    programs.CALENDARLENGTHID,
    programs.FEATURESDESCRIPTION,
    programs.WIBCOMMENT,
    programs.STATECOMMENT,
    programs.SUBMITTED,
    programs.APPROVED,
    programs.CONTACTNAME,
    programs.CONTACTPHONE,
    programs.PHONEEXTENSION as contactphoneextension,
    programs.PROGRAMID,
    programs.STATUSNAME,
    providers.NAME as providername,
    providers.SCHOOLIDENTIFICATIONNUMBER,
    providers.STREET1,
    providers.STREET2,
    providers.CITY,
    providers.STATE,
    providers.ZIP,
    providers.COUNTY,
    providers.MSTREET1,
    providers.MSTREET2,
    providers.MCITY,
    providers.MSTATE,
    providers.MZIP,
    providers.CONTACTFIRSTNAME,
    providers.CONTACTLASTNAME,
    providers.CONTACTTITLE,
    providers.PHONE,
    providers.PHONEEXTENSION,
    providers.FAX,
    providers.WEBSITE,
    providers.EMAIL,
    providers.LICENSINGAGENCYID,
    providers.TYPEID,
    providers.NONGOVAPPROVAL,
    providers.CERTAPPROVALEXP,
    providers.CUSTOMIZED,
    providers.DISTANCELEARNING,
    providers.SPEAKSPANISH,
    providers.OTHERLANGUAGES,
    providers.LANGUAGES,
    providers.CAREERASSIST,
    providers.ONESTOPCAREER,
    providers.PERSONALASSIST,
    providers.ACCESSAJBATB,
    providers.CHILDCARE,
    providers.ASSISTOBTAININGCHILDCARE,
    providers.EVENINGCOURSES,
    providers.ACCESSFORDISABLED,
    providers.BUSROUTE1,
    providers.BUSROUTE2,
    providers.TRNROUTE1,
    providers.TRNROUTE2,
    providers.WIBCOMMENT as providerwibcomment,
    providers.STATECOMMENT as providerstatecomment,
    providers.DTSUBMITTED,
    providers.STATUSNAME as providerstatusname
 FROM programs LEFT OUTER JOIN providers ON(programs.providerid = providers.providerid);

drop table programs;
drop table providers;