INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0105','Agricultural/Farm Supplies Retailing and Wholesaling.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0106','Agricultural Business Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0205','Agricultural Mechanics and Equipment/Machine Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0504','Dog/Pet/Animal Grooming.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0509','Farrier Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0601','Applied Horticulture/Horticulture Operations, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0603','Ornamental Horticulture.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0604','Greenhouse Operations and Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0605','Landscaping and Groundskeeping.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0606','Plant Nursery Operations and Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0607','Turf and Turfgrass Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0608','Floriculture/Floristry Operations and Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.0802','Agricultural Communication/Journalism.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8001','Veterinary Medicine.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8101','Veterinary Sciences/Veterinary Clinical Sciences, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8102','Comparative and Laboratory Animal Medicine.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8103','Large Animal/Food Animal and Equine Surgery and Medicine.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8104','Small/Companion Animal Surgery and Medicine.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8105','Veterinary Anatomy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8106','Veterinary Infectious Diseases.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8107','Veterinary Microbiology and Immunobiology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8108','Veterinary Pathology and Pathobiology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8109','Veterinary Physiology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8110','Veterinary Preventive Medicine, Epidemiology, and Public Health.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8111','Veterinary Toxicology and Pharmacology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8199','Veterinary Biomedical and Clinical Sciences, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8201','Veterinary Administrative Services, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8202','Veterinary Office Management/Administration.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8203','Veterinary Reception/Receptionist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8204','Veterinary Administrative/Executive Assistant and Veterinary Secretary.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8301','Veterinary/Animal Health Technology/Technician and Veterinary Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('01.8399','Veterinary/Animal Health Technologies/Technicians, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('03.0103','Environmental Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('03.0104','Environmental Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('03.0208','Environmental/Natural Resources Law Enforcement and Protective Services.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('03.0209','Energy and Environmental Policy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0201','Architecture.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0202','Architectural Design.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0401','Environmental Design/Architecture.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0801','Architectural History and Criticism, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0901','Architectural Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0902','Architectural and Building Sciences/Technology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('04.0999','Architectural Sciences and Technology, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('10.0201','Photographic and Film/Video Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('10.0203','Recording Arts Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0401','Cosmetology/Cosmetologist, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0404','Electrolysis/Electrology and Electrolysis Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0406','Make-Up Artist/Specialist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0407','Hair Styling/Stylist and Hair Design.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0408','Facial Treatment Specialist/Facialist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0409','Aesthetician/Esthetician and Skin Care Specialist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0410','Nail Technician/Specialist and Manicurist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0411','Permanent Cosmetics/Makeup and Tattooing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0412','Salon/Beauty Salon Management/Manager.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0413','Cosmetology, Barber/Styling, and Nail Instructor.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0414','Master Aesthetician/Esthetician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0499','Cosmetology and Related Personal Grooming Arts, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0500','Cooking and Related Culinary Arts, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0502','Bartending/Bartender.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0503','Culinary Arts/Chef Training.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0504','Restaurant, Culinary, and Catering Management/Manager.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('12.0507','Food Service, Waiter/Waitress, and Dining Room Management/Manager.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0201','Bilingual and Multilingual Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0301','Curriculum and Instruction.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0501','Educational/Instructional Technology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0601','Educational Evaluation and Research.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0603','Educational Statistics and Research Methods.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0604','Educational Assessment, Testing, and Measurement.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0608','Institutional Research.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.0699','Educational Assessment, Evaluation, and Research, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1201','Adult and Continuing Education and Teaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1202','Elementary Education and Teaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1206','Teacher Education, Multiple Levels.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1207','Montessori Teacher Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1208','Waldorf/Steiner Teacher Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1209','Kindergarten/Preschool Education and Teaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1210','Early Childhood Education and Teaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1211','Online Educator/Online Teaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1212','International Teaching and Learning.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1213','Science, Technology, Engineering, and Mathematics (STEM) Educational Methods.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1303','Business and Innovation/Entrepreneurship Teacher Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1310','Sales and Marketing Operations/Marketing and Distribution   Teacher Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1314','Physical Education Teaching and Coaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1327','Health Occupations Teacher Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1338','Environmental Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1339','Communication Arts and Literature Teacher Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1401','Teaching English as a Second or Foreign Language/ESL Language Instructor.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1402','Teaching French as a Second or Foreign Language.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('13.1499','Teaching English or French as a Second or Foreign Language, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.0801','Civil Engineering, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.0802','Geotechnical and Geoenvironmental Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.0803','Structural Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.0804','Transportation and Highway Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.0805','Water Resources Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.0899','Civil Engineering, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.1801','Materials Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.1901','Mechanical Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.2701','Systems Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.3301','Construction Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.3501','Industrial Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.3601','Manufacturing Engineering.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('14.3701','Operations Research.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.0101','Architectural Engineering Technologies/Technicians.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.0614','Welding Engineering Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1001','Construction Engineering Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1301','Drafting and Design Technology/Technician, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1302','CAD/CADD Drafting and/or Design Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1303','Architectural Drafting and Architectural CAD/CADD.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1304','Civil Drafting and Civil Engineering CAD/CADD.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1307','3-D Modeling and Design Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1501','Engineering/Industrial Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('15.1503','Packaging Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0203','Consumer Merchandising/Retailing Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0505','Foodservice Systems Administration/Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0604','Facilities Planning and Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0706','Child Development.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0708','Child Care and Support Services Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0709','Child Care Provider/Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0710','Developmental Services Worker.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0711','Early Childhood and Family Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('19.0905','Apparel and Textile Marketing Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0000','Legal Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0101','Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0201','Advanced Legal Research/Studies, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0202','Programs for Foreign Lawyers.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0203','American/U.S. Law/Legal Studies/Jurisprudence.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0204','Canadian Law/Legal Studies/Jurisprudence.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0205','Banking, Corporate, Finance, and Securities Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0206','Comparative Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0207','Energy, Environment, and Natural Resources Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0208','Health Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0209','International Law and Legal Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0210','International Business, Trade, and Tax Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0211','Tax Law/Taxation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0212','Intellectual Property Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0213','Patent Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0214','Agriculture Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0215','Arts and Entertainment Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0216','Compliance Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0217','Criminal Law and Procedure.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0218','Entrepreneurship Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0219','Family/Child/Elder Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0220','Human Resources Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0221','Insurance Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0222','Real Estate and Land Development Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0223','Transportation Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0224','Tribal/Indigenous Law.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0299','Legal Research and Advanced Professional Studies, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('22.0302','Legal Assistant/Paralegal.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0202','Biochemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0203','Biophysics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0205','Molecular Biochemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0206','Molecular Biophysics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0207','Structural Biology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0210','Biochemistry and Molecular Biology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0401','Cell/Cellular Biology and Histology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0403','Anatomy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0404','Developmental Biology and Embryology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0499','Cell/Cellular Biology and Anatomical Sciences, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0503','Medical Microbiology and Bacteriology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0913','Biomechanics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.0999','Physiology, Pathology, and Related Sciences, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1001','Pharmacology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1002','Molecular Pharmacology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1003','Neuropharmacology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1004','Toxicology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1005','Molecular Toxicology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1006','Environmental Toxicology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1007','Pharmacology and Toxicology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1099','Pharmacology and Toxicology, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1102','Biostatistics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1309','Epidemiology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('26.1311','Epidemiology and Biostatistics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('27.0601','Applied Statistics, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.1101','Gerontology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.1601','Accounting and Computer Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.1901','Nutrition Sciences.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.2502','Contemplative Studies/Inquiry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.2801','Dispute Resolution.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.3401','Anthrozoology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.4101','Environmental Geosciences.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.5301','Thanatology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.7101','Data Analytics, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.7102','Business Analytics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.7103','Data Visualization.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.7104','Financial Analytics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('30.7199','Data Analytics, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('31.0302','Golf Course Operation and Grounds Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('31.0501','Sports, Kinesiology, and Physical Education/Fitness, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('31.0504','Sport and Fitness Administration/Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('31.0507','Physical Fitness Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('31.0601','Outdoor Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0501','Chemistry, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0502','Analytical Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0503','Inorganic Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0504','Organic Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0506','Physical Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0507','Polymer Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0508','Chemical Physics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0509','Environmental Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0510','Forensic Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0511','Theoretical Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0512','Cheminformatics/Chemistry Informatics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.0599','Chemistry, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('40.1002','Materials Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('42.2709','Psychopharmacology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('42.2804','Industrial and Organizational Psychology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('42.2815','Performance and Sport Psychology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('43.0121','Suspension and Debarment Investigation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('43.0405','Financial Forensics and Fraud Investigation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('44.0000','Human Services, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('44.0503','Health Policy Analysis.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('44.0701','Social Work.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('44.0703','Forensic Social Work.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('44.0799','Social Work, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('45.0199','Social Sciences, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('45.0602','Applied Economics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('46.0302','Electrician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('46.0401','Building/Property Maintenance.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('46.0402','Concrete Finishing/Concrete Finisher.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('46.0502','Pipefitting/Pipefitter and Sprinkler Fitter.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('46.0503','Plumbing Technology/Plumber.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('46.0599','Plumbing and Related Water Supply Services, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0302','Heavy Equipment Maintenance Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0303','Industrial Mechanics and Maintenance Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0607','Airframe Mechanics and Aircraft Maintenance Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0608','Aircraft Powerplant Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0701','Energy Systems Installation and Repair Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0705','Hydroelectric Energy System Installation and Repair Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('47.0706','Geothermal Energy System Installation and Repair Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('48.0508','Welding Technology/Welder.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('49.0202','Construction/Heavy Equipment/Earthmoving Equipment Operation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('49.0205','Truck and Bus Driver/Commercial Vehicle Operator and Instructor.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('49.0206','Mobil Crane Operator/Operation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('49.0209','Forklift Operation/Operator.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0101','Chiropractic.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0201','Communication Sciences and Disorders, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0202','Audiology/Audiologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0203','Speech-Language Pathology/Pathologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0204','Audiology/Audiologist and Speech-Language Pathology/Pathologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0299','Communication Disorders Sciences and Services, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0401','Dentistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0501','Dental Clinical Sciences, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0502','Advanced General Dentistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0504','Dental Public Health and Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0505','Dental Materials.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0506','Endodontics/Endodontology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0507','Oral/Maxillofacial Surgery.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0508','Orthodontics/Orthodontology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0509','Pediatric Dentistry/Pedodontics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0510','Periodontics/Periodontology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0511','Prosthodontics/Prosthodontology.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0512','Digital Dentistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0513','Geriatric Dentistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0514','Implantology/Implant Dentistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0599','Advanced/Graduate Dentistry and Oral Sciences, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0601','Dental Assisting/Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0602','Dental Hygiene/Hygienist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0603','Dental Laboratory Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0702','Hospital and Health Care Facilities Administration/Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0705','Medical Office Management/Administration.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0711','Medical/Health Management and Clinical Assistant/Specialist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0712','Medical Reception/Receptionist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0717','Medical Staff Services Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0720','Regulatory Science/Affairs.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0801','Medical/Clinical Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0802','Clinical/Medical Laboratory Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0803','Occupational Therapist Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0805','Pharmacy Technician/Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0809','Anesthesiologist Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0813','Chiropractic Technician/Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0901','Cardiovascular Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0902','Electrocardiograph Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0903','Electroneurodiagnostic/Electroencephalographic Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0904','Emergency Medical Technology/Technician (EMT Paramedic).');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0905','Nuclear Medical Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0906','Perfusion Technology/Perfusionist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0907','Medical Radiologic Technology/Science - Radiation Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0908','Respiratory Care Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0909','Surgical Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0910','Diagnostic Medical Sonography/Sonographer and Ultrasound Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0911','Radiologic Technology/Science - Radiographer.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0912','Physician Assistant.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0913','Athletic Training/Trainer.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0914','Gene/Genetic Therapy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0915','Cardiopulmonary Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0916','Radiation Protection/Health Physics Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0917','Polysomnography.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0919','Mammography Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0920','Magnetic Resonance Imaging (MRI) Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0921','Hyperbaric Medicine Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0922','Intraoperative Neuromonitoring Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0923','Orthopedic Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.0999','Allied Health Diagnostic, Intervention, and Treatment Professions, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1001','Blood Bank Technology Specialist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1002','Cytotechnology/Cytotechnologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1003','Hematology Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1004','Clinical/Medical Laboratory Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1005','Clinical Laboratory Science/Medical Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1006','Ophthalmic Laboratory Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1007','Histologic Technology/Histotechnologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1008','Histologic Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1009','Phlebotomy Technician/Phlebotomist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1010','Cytogenetics/Genetics/Clinical Genetics Technology/Technologist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1011','Renal/Dialysis Technologist/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1012','Sterile Processing Technology/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1099','Clinical/Medical Laboratory Science and Allied Professions, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1405','Tropical Medicine.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1501','Substance Abuse/Addiction Counseling.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1503','Clinical/Medical Social Work.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1511','Medical Family Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.1512','Hospice and Palliative Care.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2001','Pharmacy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2002','Pharmacy Administration and Pharmacy Policy and Regulatory Affairs.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2003','Pharmaceutics and Drug Design.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2004','Medicinal and Pharmaceutical Chemistry.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2005','Natural Products Chemistry and Pharmacognosy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2006','Clinical and Industrial Drug Development.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2007','Pharmacoeconomics/Pharmaceutical Economics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2008','Clinical, Hospital, and Managed Care Pharmacy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2009','Industrial and Physical Pharmacy and Cosmetic Sciences.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2010','Pharmaceutical Sciences.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2011','Pharmaceutical Marketing and Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2099','Pharmacy, Pharmaceutical Sciences, and Administration, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2201','Public Health, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2202','Environmental Health.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2205','Health/Medical  Physics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2206','Occupational Health and Industrial Hygiene.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2207','Public Health Education and Promotion.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2208','Community Health and Preventive Medicine.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2209','Maternal and Child Health.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2212','Behavioral Aspects of Health.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2213','Patient Safety and Healthcare Quality.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2214','Public Health Genetics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2299','Public Health, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2300','Rehabilitation and Therapeutic Professions, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2301','Art Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2302','Dance Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2305','Music Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2306','Occupational Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2307','Orthotist/Prosthetist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2308','Physical Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2309','Therapeutic Recreation/Recreational Therapy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2310','Vocational Rehabilitation Counseling/Counselor.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2311','Kinesiotherapy/Kinesiotherapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2313','Animal-Assisted Therapy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2314','Rehabilitation Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2315','Drama Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2316','Horticulture Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2317','Play Therapy/Therapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2399','Rehabilitation and Therapeutic Professions, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2604','Rehabilitation Aide.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.2605','Physical Therapy Technician/Aide.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3202','Health Professions Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3203','Nursing Education.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3501','Massage Therapy/Therapeutic Massage.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3502','Asian Bodywork Therapy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3503','Somatic Bodywork.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3599','Somatic Bodywork and Related Therapeutic Services, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3602','Yoga Teacher Training/Yoga Therapy.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3603','Hypnotherapy/Hypnotherapist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3801','Registered Nursing/Registered Nurse.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3802','Nursing Administration.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3803','Adult Health Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3804','Nurse Anesthetist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3805','Family Practice Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3806','Maternal/Child Health and Neonatal Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3807','Nurse Midwife/Nursing Midwifery.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3808','Nursing Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3809','Pediatric Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3810','Psychiatric/Mental Health Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3811','Public Health/Community Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3812','Perioperative/Operating Room and Surgical Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3813','Clinical Nurse Specialist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3814','Critical Care Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3815','Occupational and Environmental Health Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3816','Emergency Room/Trauma Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3818','Nursing Practice.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3819','Palliative Care Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3820','Clinical Nurse Leader.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3821','Geriatric Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3822','Women"s Health Nurse/Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3824','Forensic Nursing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3899','Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3901','Licensed Practical/Vocational Nurse Training.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('51.3999','Practical Nursing, Vocational Nursing and Nursing Assistants, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0101','Business/Commerce, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0201','Business Administration and Management, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0202','Purchasing, Procurement/Acquisitions and Contracts Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0203','Logistics, Materials, and Supply Chain Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0204','Office Management and Supervision.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0205','Operations Management and Supervision.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0206','Non-Profit/Public/Organizational Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0207','Customer Service Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0208','E-Commerce/Electronic Commerce.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0210','Research and Development Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0211','Project Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0212','Retail Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0213','Organizational Leadership.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0301','Accounting.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0302','Accounting Technology/Technician and Bookkeeping.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0303','Auditing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0304','Accounting and Finance.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0305','Accounting and Business/Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0401','Administrative Assistant and Secretarial Science, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0402','Executive Assistant/Executive Secretary.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0406','Receptionist.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0408','General Office Occupations and Clerical Services.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0409','Parts, Warehousing, and Inventory Management Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0410','Traffic, Customs, and Transportation Clerk/Technician.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0411','Customer Service Support/Call Center/Teleservice Operation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0501','Business/Corporate Communications, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0599','Business/Corporate Communications, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0601','Business/Managerial Economics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0701','Entrepreneurship/Entrepreneurial Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0702','Franchising and Franchise Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0801','Finance, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0804','Financial Planning and Services.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0806','International Finance.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0807','Investments and Securities.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0808','Public Finance.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0810','Financial Risk Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0907','Meeting and Event Planning.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.0909','Hotel, Motel, and Restaurant Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1001','Human Resources Management/Personnel Administration, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1002','Labor and Industrial Relations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1003','Organizational Behavior Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1004','Labor Studies.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1006','Executive/Career Coaching.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1099','Human Resources Management and Services, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1101','International Business/Trade/Commerce.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1301','Management Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1302','Business Statistics.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1304','Actuarial Science.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1401','Marketing/Marketing Management, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1402','Marketing Research.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1403','International Marketing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1404','Digital Marketing.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1499','Marketing, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1601','Taxation.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1701','Insurance.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1801','Sales, Distribution, and Marketing Operations, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1803','Retailing and Retail Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1804','Selling Skills and Sales Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1899','General Merchandising, Sales, and Related Marketing Operations, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1902','Fashion Merchandising.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1904','Apparel and Accessories Marketing Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1905','Tourism and Travel Services Marketing Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1906','Tourism Promotion Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1907','Vehicle and Vehicle Parts and Accessories Marketing Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1908','Business and Personal/Financial Services Marketing Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1909','Special Products Marketing Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.1910','Hospitality and Recreation Marketing Operations.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.2002','Construction Project Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.2099','Construction Management, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('52.2101','Telecommunications Management.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0102','Dental Public Health Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0106','Pediatric Dentistry Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0701','Nurse Practitioner Residency/Fellowship Program, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0702','Combined Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0703','Acute Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0704','Adult/Gerontology Acute Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0705','Adult/Gerontology Critical Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0706','Cardiology/Cardiovascular Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0707','Clinical Informatics Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0708','Dermatology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0709','Developmental and Behavioral Pediatrics Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0710','Diabetes Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0711','Emergency Medicine Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0712','Endocrinology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0713','Family Medicine Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0714','Gastroenterology and Hepatology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0715','Gastroenterology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0716','Genetics Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0717','Gerontology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0718','Global Health Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0719','Hematology-Oncology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0720','Hepatology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0721','Home-Based Primary Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0722','Hospice and Palliative Medicine Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0723','Hospital Medicine Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0724','Infectious Diseases Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0725','Neonatal Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0726','Nephrology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0727','Neurology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0728','Neuroscience Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0729','Obstetrics and Gynecology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0730','Occupational Health Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0731','Orthopedic Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0732','Orthopedic Surgery Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0733','Pain Management Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0734','Palliative Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0735','Pediatric Hematology-Oncology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0736','Pediatric Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0737','Pediatric Rehabilitation Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0738','Psychiatric/Mental Health Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0739','Public/Community Health Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0740','Pulmonary Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0741','Rheumatology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0742','Rural Health Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0743','Sleep Medicine Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0744','Surgical and Critical Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0745','Surgical Wound and Reconstruction Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0746','Transplantation Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0747','Trauma and Critical Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0748','Urgent Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0749','Urology Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0750','Women''s Health Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0751','Wound Care Nurse Practitioner Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0799','Nurse Practitioner Residency/Fellowship Program, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0901','Physician Assistant Residency/Fellowship Program, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0902','Combined Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0903','Acute Care Medicine Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0904','Acute Care Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0905','Cardiology Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0906','Cardiothoracic Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0907','Critical Care Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0908','Critical Care and Trauma Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0909','Emergency Medicine Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0910','ENT Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0911','Family Medicine Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0912','Geriatrics Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0913','Hematology-Oncology Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0914','Hepatobiliary Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0915','Hospitalist Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0916','Neurosurgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0917','Orthopedic Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0918','Pediatric Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0919','Transplant Surgery Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0920','Urology Physician Assistant Residency/Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('60.0999','Physician Assistant Residency/Fellowship Program, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0101','Combined Medical Residency/Fellowship Program, General.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0102','Diagnostic Radiology/Nuclear Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0103','Emergency Medicine/Anesthesiology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0104','Family Medicine/Emergency Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0105','Family Medicine/Osteopathic Neuromusculoskeletal Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0106','Family Medicine/Preventive Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0107','Family Medicine/Psychiatry Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0108','Internal Medicine/Anesthesiology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0109','Internal Medicine/Dermatology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0110','Internal Medicine/Emergency Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0111','Internal Medicine/Emergency Medicine/Critical Care Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0112','Internal Medicine/Family Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0113','Internal Medicine/Medical Genetics and Genomics Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0114','Internal Medicine/Neurology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0115','Internal Medicine/Pediatrics Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0116','Internal Medicine/Preventive Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0117','Internal Medicine/Psychiatry Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0118','Medical Genetics and Genomics/Maternal-Fetal Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0119','Pediatrics/Anesthesiology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0120','Pediatrics/Emergency Medicine Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0121','Pediatrics/Medical Genetics and Genomics Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0122','Pediatrics/Physical Medicine & Rehabilitation Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0123','Pediatrics/Psychology/Child-Adolescent Psychology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0124','Psychiatry/Neurology Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0125','Reproductive Endocrinology and Infertility/Medical Genetics and Genomics Combined Specialty Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0199','Combined Medical Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0202','Critical Care Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0203','Geriatric Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0204','Health Policy Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0205','Hospice and Palliative Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0206','Integrative Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0207','Medical Education Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0208','Medical Toxicology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0209','Neuromuscular Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0210','Pain Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0211','Simulation Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0212','Sleep Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0213','Sports Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0214','Surgery of the Hand Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0215','Telemedicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0216','Undersea and Hyperbaric Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0217','Wilderness Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0218','Women''s Health Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0299','Multiple-Pathway Medical Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0301','Allergy and Immunology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0399','Allergy and Immunology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0401','Anesthesiology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0499','Anesthesiology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0501','Dermatology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0502','Dermatopathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0503','Pediatric Dermatology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0599','Dermatology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0601','Emergency Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0602','Disaster Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0603','Emergency Medical Services Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0699','Emergency Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0701','Family Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0799','Family Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0801','Internal Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0804','Cardiovascular Disease Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0805','Clinical Cardiac Electrophysiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0806','Endocrinology, Diabetes, and Metabolism Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0807','Gastroenterology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0808','Hematology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0809','Hematology-Oncology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0810','Infectious Disease Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0811','Interventional Cardiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0812','Nephrology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0813','Medical Oncology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0814','Pulmonary Disease Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0816','Rheumatology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0818','Transplant Hepatology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0899','Internal Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0901','Clinical Biochemical Genetics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0902','Clinical Genetics and Genomics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0903','Laboratory Genetics and Genomics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0904','Medical Biochemical Genetics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.0999','Medical Genetics and Genomics Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1001','Neurological Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1099','Neurological Surgery Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1101','Neurology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1102','Child Neurology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1103','Clinical Neurophysiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1104','Epilepsy Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1105','Headache Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1106','Neurodevelopmental Disabilities Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1107','Vascular Neurology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1199','Neurology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1201','Nuclear Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1299','Nuclear Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1301','Obstetrics and Gynecology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1302','Gynecologic Oncology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1303','Maternal and Fetal Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1304','Reproductive Endocrinology/Infertility Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1399','Obstetrics and Gynecology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1401','Ophthalmology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1499','Ophthalmology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1501','Orthopedic Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1502','Musculoskeletal Oncology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1503','Orthopedic Sports Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1504','Orthopedic Surgery of the Spine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1505','Pediatric Orthopedics Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1599','Orthopedic Surgery Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1601','Osteopathic Neuromusculoskeletal Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1699','Osteopathic Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1701','Otolaryngology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1702','Neurotology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1703','Pediatric Otolaryngology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1799','Otolaryngology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1801','Combined Anatomic and Clinical Pathology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1802','Anatomic Pathology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1803','Clinical Pathology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1804','Blood Banking/Transfusion Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1805','Chemical Pathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1806','Cytopathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1807','Forensic Pathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1808','Hematological Pathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1809','Immunopathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1810','Laboratory Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1811','Medical Microbiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1812','Molecular Genetic Pathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1813','Neuropathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1814','Pediatric Pathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1815','Radioisotopic Pathology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1899','Pathology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1901','Pediatrics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1902','Adolescent Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1903','Child Abuse Pediatrics Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1904','Developmental-Behavioral Pediatrics Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1905','Neonatal-Perinatal Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1906','Pediatric Cardiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1907','Pediatric Critical Care Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1908','Pediatric Emergency Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1909','Pediatric Endocrinology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1910','Pediatric Gastroenterology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1911','Pediatric Hematology-Oncology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1912','Pediatric Infectious Diseases Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1913','Pediatric Nephrology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1914','Pediatric Pulmonology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1915','Pediatric Rheumatology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1917','Pediatric Transplant Hepatology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.1999','Pediatrics Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2001','Physical Medicine and Rehabilitation Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2002','Spinal Cord Injury Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2003','Pediatric Rehabilitation Medicine Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2099','Physical Medicine and Rehabilitation Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2101','Plastic Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2102','Integrated Plastic Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2103','Plastic Surgery Within the Head and Neck Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2199','Plastic Surgery Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2201','Podiatric Medicine and Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2299','Podiatric Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2301','Public Health and General Preventive Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2302','Aerospace Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2303','Occupational Medicine Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2399','Preventive Medicine Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2401','Psychiatry Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2402','Addiction Psychiatry Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2403','Child and Adolescent Psychiatry Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2404','Consultation-Liaison Psychiatry Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2405','Forensic Psychiatry Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2406','Geriatric Psychiatry Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2499','Psychiatry Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2501','Radiation Oncology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2599','Radiation Oncology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2601','Diagnostic Radiology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2602','Integrated Interventional Radiology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2603','Abdominal Radiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2604','Diagnostic Radiologic Physics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2605','Medical Nuclear Physics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2606','Musculoskeletal Radiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2607','Neuroradiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2608','Nuclear Radiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2609','Pediatric Radiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2610','Radiologic Physics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2611','Therapeutic Radiologic Physics Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2612','Vascular and Interventional Radiology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2699','Radiology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2701','General Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2702','Colon and Rectal Surgery Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2703','Complex General Surgical Oncology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2704','Congenital Cardiac Surgery Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2705','Pediatric Surgery Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2706','Surgical Critical Care Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2707','Thoracic Surgery Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2708','Vascular Surgery Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2799','Surgery Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2801','Urology Residency Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2802','Pediatric Urology Fellowship Program.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.2899','Urology Residency/Fellowship Programs, Other.');
INSERT INTO indemandcips (CIP,CIPTitle) values ('61.9999','Medical Residency/Fellowship Programs, Other.');
