CREATE TABLE IF NOT EXISTS oesestimates(
  area integer,
  area_title text,
  area_type integer,
  naics integer,
  naics_title text,
  i_group text,
  own_code integer,
  occ_code character varying(32),
  occ_title text,
  o_group character varying(32),
  tot_emp character varying(32),
  emp_prse character varying(32),
  jobs_1000 character varying(32),
  loc_quotient character varying(32),
  pct_total character varying(32),
  h_mean character varying(32),
  a_mean character varying(32),
  mean_prse character varying(32),
  h_pct10 character varying(32),
  h_pct25 character varying(32),
  h_median character varying(32),
  h_pct75 character varying(32),
  h_pct90 character varying(32),
  a_pct10 character varying(32),
  a_pct25 character varying(32),
  a_median character varying(32),
  a_pct75 character varying(32),
  a_pct90 character varying(32),
  annual boolean,
  hourly boolean
);

