INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1041','Compliance Officers, Except Agriculture, Construction, Health and Safety, and Transportation');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1051','Cost Estimators');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1071','Human Resources Specialists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1081','Logisticians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1111','Management Analysts');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1121','Meeting, Convention, and Event Planners');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-1161','Market Research Analysts and Marketing Specialists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-2011','Accountants and Auditors');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('13-2061','Financial Examiners');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('15-1122','Information Security Analysts');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('15-1132','Software Developers, Applications');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('15-1134','Web Developers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('15-2031','Operations Research Analysts');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('17-1011','Architects, Except Landscape and Naval');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('17-2051','Civil Engineers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('17-2112','Industrial Engineers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('17-3011','Architectural and Civil Drafters');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('19-1021','Biochemists and Biophysicists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('19-2031','Chemists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('21-1022','Healthcare Social Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('21-1093','Social and Human Service Assistants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('23-1011','Lawyers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('23-2011','Paralegals and Legal Assistants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-1011','Business Teachers, Postsecondary');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-1071','Health Specialties Teachers, Postsecondary');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-1072','Nursing Instructors and Teachers, Postsecondary');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-2011','Preschool Teachers, Except Special Education');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-2021','Elementary School Teachers, Except Special Education');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-3021','Self-Enrichment Education Teachers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('25-9031','Instructional Coordinators');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('27-2022','Coaches and Scouts');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('27-4011','Audio and Video Equipment Technicians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1021','Dentists, General');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1069','Physicians and Surgeons, All Other');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1071','Physician Assistants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1122','Occupational Therapists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1123','Physical Therapists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1126','Respiratory Therapists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1127','Speech-Language Pathologists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1141','Registered Nurses');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-1171','Nurse Practitioners');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-2032','Diagnostic Medical Sonographers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-2034','Radiologic Technologists and Technicians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-2052','Pharmacy Technicians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-2056','Veterinary Technologists and Technicians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('29-2061','Licensed Practical and Licensed Vocational Nurses');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-1011','Home Health Aides');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-1014','Nursing Assistants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-2022','Physical Therapist Aides');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-9011','Massage Therapists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-9091','Dental Assistants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-9092','Medical Assistants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-9093','Medical Equipment Preparers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('31-9097','Phlebotomists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('33-9092','Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-1012','First-Line Supervisors of Food Preparation and Serving Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-2014','Cooks, Restaurant');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-2021','Food Preparation Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-3011','Bartenders');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-3021','Combined Food Preparation and Serving Workers, Including Fast Food');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-3022','Counter Attendants, Cafeteria, Food Concession, and Coffee Shop');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-3031','Waiters and Waitresses');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-9011','Dining Room and Cafeteria Attendants and Bartender Helpers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('35-9031','Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('37-1011','First-Line Supervisors of Housekeeping and Janitorial Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('37-2011','Janitors and Cleaners, Except Maids and Housekeeping Cleaners');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('37-3011','Landscaping and Groundskeeping Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-1021','First-Line Supervisors of Personal Service Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-2021','Nonfarm Animal Caretakers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-3031','Ushers, Lobby Attendants, and Ticket Takers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-3091','Amusement and Recreation Attendants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-5012','Hairdressers, Hairstylists, and Cosmetologists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-5092','Manicurists and Pedicurists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-5094','Skincare Specialists');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-9011','Childcare Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-9021','Personal Care Aides');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-9031','Fitness Trainers and Aerobics Instructors');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('39-9032','Recreation Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-1011','First-Line Supervisors of Retail Sales Workers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-2031','Retail Salespersons');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-3021','Insurance Sales Agents');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-3041','Travel Agents');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-3099','Sales Representatives, Services, All Other');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-4012','Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('41-9011','Demonstrators and Product Promoters');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-1011','First-Line Supervisors of Office and Administrative Support Worke');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-3031','Bookkeeping, Accounting, and Auditing Clerks');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-4051','Customer Service Representatives');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-4171','Receptionists and Information Clerks');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-4181','Reservation and Transportation Ticket Agents and Travel Clerks');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-5011','Cargo and Freight Agents');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-5061','Production, Planning, and Expediting Clerks');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-5111','Weighers, Measurers, Checkers, and Samplers, Recordkeeping');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('43-9041','Insurance Claims and Policy Processing Clerks');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('47-2051','Cement Masons and Concrete Finishers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('47-2073','Operating Engineers and Other Construction Equipment Operators');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('47-2111','Electricians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('47-2152','Plumbers, Pipefitters, and Steamfitters');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('49-3011','Aircraft Mechanics and Service Technicians');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('49-3042','Mobile Heavy Equipment Mechanics, Except Engines');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('49-9041','Industrial Machinery Mechanics');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('49-9071','Maintenance and Repair Workers, General');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('51-3022','Meat, Poultry, and Fish Cutters and Trimmers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('51-4121','Welders, Cutters, Solderers, and Brazers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('53-3032','Heavy and Tractor-Trailer Truck Drivers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('53-3033','Light Truck or Delivery Services Drivers');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('53-6021','Parking Lot Attendants');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('53-7051','Industrial Truck and Tractor Operators');
INSERT INTO indemandsocs (SOC,OCCUPATIONTITLE) values ('53-7062','Laborers and Freight, Stock, and Material Movers, Hand');
