CREATE TABLE IF NOT EXISTS outcomes_programid (
    provider_id character varying(32),
    provider_combo character varying(255),
    program_id character varying(16) UNIQUE,
    program_name_upd character varying(255),
    exiters integer,
    completers integer,
    n_employed_q2 integer,
    employment_rate_q2 decimal,
    n_employed_q4 integer,
    employment_rate_q4 decimal,
    median_q2_annual decimal,
    median_q4_annual decimal,
    completion_rate decimal,
    credential_rate decimal,
    quarter2_naics1_code character varying(16),
    quarter2_naics1_title character varying(255),
    quarter2_naics2_code character varying(16),
    quarter2_naics2_title character varying(255),
    quarter2_naics3_code character varying(16),
    quarter2_naics3_title character varying(255),
    quarter4_naics1_code character varying(16),
    quarter4_naics1_title character varying(255),
    quarter4_naics2_code character varying(16),
    quarter4_naics2_title character varying(255),
    quarter4_naics3_code character varying(16),
    quarter4_naics3_title character varying(255),
    id serial NOT NULL PRIMARY KEY
);