TRUNCATE TABLE indemandsocs;
TRUNCATE TABLE indemandsocs;

INSERT INTO indemandsocs (soc, occupationtitle) VALUES
                                             ('11-3021', 'Computer and Information Systems Managers'),
                                             ('11-3031', 'Financial Managers'),
                                             ('11-3071', 'Transportation, Storage, and Distribution Managers'),
                                             ('11-9021', 'Construction Managers'),
                                             ('11-9033', 'Education Administrators, Postsecondary'),
                                             ('11-9051', 'Food Service Managers'),
                                             ('11-9111', 'Medical and Health Services Managers'),
                                             ('11-9121', 'Natural Sciences Managers'),
                                             ('11-9151', 'Social and Community Service Managers'),
                                             ('13-1071', 'Human Resources Specialists'),
                                             ('13-1081', 'Logisticians'),
                                             ('13-1082', 'Project Management Specialists'),
                                             ('13-1111', 'Management Analysts'),
                                             ('13-1121', 'Meeting, Convention, and Event Planners'),
                                             ('13-1151', 'Training and Development Specialists'),
                                             ('13-1161', 'Market Research Analysts and Marketing Specialists'),
                                             ('13-2052', 'Personal Financial Advisors'),
                                             ('13-2061', 'Financial Examiners'),
                                             ('15-1211', 'Computer Systems Analysts'),
                                             ('15-1212', 'Information Security Analysts'),
                                             ('15-1252', 'Software Developers'),
                                             ('15-1253', 'Software Quality Assurance Analysts and Testers'),
                                             ('15-1254', 'Web Developers'),
                                             ('15-1255', 'Web and Digital Interface Designers'),
                                             ('15-2031', 'Operations Research Analysts'),
                                             ('15-2051', 'Data Scientists'),
                                             ('17-2071', 'Electrical Engineers'),
                                             ('17-2112', 'Industrial Engineers'),
                                             ('17-2141', 'Mechanical Engineers'),
                                             ('19-1021', 'Biochemists and Biophysicists'),
                                             ('19-1042', 'Medical Scientists, Except Epidemiologists'),
                                             ('19-2031', 'Chemists'),
                                             ('19-2041', 'Environmental Scientists and Specialists, Including Health'),
                                             ('19-3033', 'Clinical and Counseling Psychologists'),
                                             ('19-4031', 'Chemical Technicians'),
                                             ('19-5011', 'Occupational Health and Safety Specialists'),
                                             ('21-1012', 'Educational, Guidance, and Career Counselors and Advisors'),
                                             ('21-1018', 'Substance Abuse, Behavioral Disorder, and Mental Health Counselors'),
                                             ('21-1021', 'Child, Family, and School Social Workers'),
                                             ('21-1022', 'Healthcare Social Workers'),
                                             ('21-1023', 'Mental Health and Substance Abuse Social Workers'),
                                             ('21-1093', 'Social and Human Service Assistants'),
                                             ('21-1099', 'Community and Social Service Specialists, All Other'),
                                             ('23-1011', 'Lawyers'),
                                             ('25-1011', 'Business Teachers, Postsecondary'),
                                             ('25-1071', 'Health Specialties Teachers, Postsecondary'),
                                             ('25-1072', 'Nursing Instructors and Teachers, Postsecondary'),
                                             ('25-1081', 'Education Teachers, Postsecondary'),
                                             ('25-1121', 'Art, Drama, and Music Teachers, Postsecondary'),
                                             ('25-1194', 'Career/Technical Education Teachers, Postsecondary'),
                                             ('25-3021', 'Self-Enrichment Teachers'),
                                             ('25-3031', 'Substitute Teachers, Short-Term'),
                                             ('25-3041', 'Tutors'),
                                             ('25-9044', 'Teaching Assistants, Postsecondary'),
                                             ('27-1026', 'Merchandise Displayers and Window Trimmers'),
                                             ('27-2022', 'Coaches and Scouts'),
                                             ('27-3031', 'Public Relations Specialists'),
                                             ('29-1021', 'Dentists, General'),
                                             ('29-1031', 'Dietitians and Nutritionists'),
                                             ('29-1071', 'Physician Assistants'),
                                             ('29-1122', 'Occupational Therapists'),
                                             ('29-1123', 'Physical Therapists'),
                                             ('29-1126', 'Respiratory Therapists'),
                                             ('29-1127', 'Speech-Language Pathologists'),
                                             ('29-1141', 'Registered Nurses'),
                                             ('29-1171', 'Nurse Practitioners'),
                                             ('29-1215', 'Family Medicine Physicians'),
                                             ('29-1229', 'Physicians, All Other'),
                                             ('29-1292', 'Dental Hygienists'),
                                             ('29-2011', 'Medical and Clinical Laboratory Technologists'),
                                             ('29-2012', 'Medical and Clinical Laboratory Technicians'),
                                             ('29-2032', 'Diagnostic Medical Sonographers'),
                                             ('29-2034', 'Radiologic Technologists and Technicians'),
                                             ('29-2042', 'Emergency Medical Technicians'),
                                             ('29-2052', 'Pharmacy Technicians'),
                                             ('29-2055', 'Surgical Technologists'),
                                             ('29-2056', 'Veterinary Technologists and Technicians'),
                                             ('29-2061', 'Licensed Practical and Licensed Vocational Nurses'),
                                             ('29-2072', 'Medical Records Specialists'),
                                             ('29-2081', 'Opticians, Dispensing'),
                                             ('29-2099', 'Health Technologists and Technicians, All Other'),
                                             ('31-1121', 'Home Health Aides'),
                                             ('31-1122', 'Personal Care Aides'),
                                             ('31-2021', 'Physical Therapist Assistants'),
                                             ('31-2022', 'Physical Therapist Aides'),
                                             ('31-9011', 'Massage Therapists'),
                                             ('31-9091', 'Dental Assistants'),
                                             ('31-9092', 'Medical Assistants'),
                                             ('31-9093', 'Medical Equipment Preparers'),
                                             ('31-9097', 'Phlebotomists'),
                                             ('31-9099', 'Healthcare Support Workers, All Other'),
                                             ('33-9092', 'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers'),
                                             ('35-1011', 'Chefs and Head Cooks'),
                                             ('35-1012', 'First-Line Supervisors of Food Preparation and Serving Workers'),
                                             ('35-2012', 'Cooks, Institution and Cafeteria'),
                                             ('35-2014', 'Cooks, Restaurant'),
                                             ('35-3011', 'Bartenders'),
                                             ('35-3023', 'Fast Food and Counter Workers'),
                                             ('35-3041', 'Food Servers, Nonrestaurant'),
                                             ('35-9011', 'Dining Room and Cafeteria Attendants and Bartender Helpers'),
                                             ('35-9031', 'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop'),
                                             ('35-9099', 'Food Preparation and Serving Related Workers, All Other'),
                                             ('37-1012', 'First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers'),
                                             ('37-2021', 'Pest Control Workers'),
                                             ('37-3011', 'Landscaping and Groundskeeping Workers'),
                                             ('37-3013', 'Tree Trimmers and Pruners'),
                                             ('39-1014', 'First-Line Supervisors of Entertainment & Rec Workers, Except Gambling Services'),
                                             ('39-1022', 'First-Line Supervisors of Personal Service Workers'),
                                             ('39-2021', 'Animal Caretakers'),
                                             ('39-3031', 'Ushers, Lobby Attendants, and Ticket Takers'),
                                             ('39-3091', 'Amusement and Recreation Attendants'),
                                             ('39-5012', 'Hairdressers, Hairstylists, and Cosmetologists'),
                                             ('39-5092', 'Manicurists and Pedicurists'),
                                             ('39-6012', 'Concierges'),
                                             ('39-9031', 'Exercise Trainers and Group Fitness Instructors'),
                                             ('39-9032', 'Recreation Workers'),
                                             ('39-9099', 'Personal Care and Service Workers, All Other'),
                                             ('41-2021', 'Counter and Rental Clerks'),
                                             ('41-4011', 'Sales Representatives, Wholesale and Mfg, Technical and Scientific Products'),
                                             ('41-9099', 'Sales and Related Workers, All Other'),
                                             ('43-4171', 'Receptionists and Information Clerks'),
                                             ('43-5011', 'Cargo and Freight Agents'),
                                             ('43-5061', 'Production, Planning, and Expediting Clerks'),
                                             ('43-6013', 'Medical Secretaries and Administrative Assistants'),
                                             ('47-2061', 'Construction Laborers'),
                                             ('47-2073', 'Operating Engineers and Other Construction Equipment Operators'),
                                             ('47-2111', 'Electricians'),
                                             ('47-2152', 'Plumbers, Pipefitters, and Steamfitters'),
                                             ('47-4051', 'Highway Maintenance Workers'),
                                             ('49-3042', 'Mobile Heavy Equipment Mechanics, Except Engines'),
                                             ('49-9021', 'Heating, Air Conditioning, and Refrigeration Mechanics and Installers'),
                                             ('49-9041', 'Industrial Machinery Mechanics'),
                                             ('51-2022', 'Electrical and Electronic Equipment Assemblers'),
                                             ('51-2023', 'Electromechanical Equipment Assemblers'),
                                             ('51-3011', 'Bakers'),
                                             ('51-3092', 'Food Batchmakers'),
                                             ('51-4041', 'Machinists'),
                                             ('51-4081', 'Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic'),
                                             ('51-4121', 'Welders, Cutters, Solderers, and Brazers'),
                                             ('51-9111', 'Packaging and Filling Machine Operators and Tenders'),
                                             ('51-9199', 'Production Workers, All Other'),
                                             ('53-1047', 'First-Line Supervisors of Transportation and Material-Moving Workers, Except Aircraft Cargo Handling Supervisors'),
                                             ('53-2031', 'Flight Attendants'),
                                             ('53-3031', 'Driver/Sales Workers'),
                                             ('53-3032', 'Heavy and Tractor-Trailer Truck Drivers'),
                                             ('53-3033', 'Light Truck Drivers'),
                                             ('53-3053', 'Shuttle Drivers and Chauffeurs'),
                                             ('53-3099', 'Motor Vehicle Operators, All Other'),
                                             ('53-7051', 'Industrial Truck and Tractor Operators'),
                                             ('53-7062', 'Laborers and Freight, Stock, and Material Movers, Hand'),
                                             ('53-7064', 'Packers and Packagers, Hand'),
                                             ('53-7065', 'Stockers and Order Fillers');

TRUNCATE TABLE indemandcips;

-- Insert new CIP codes based on current in-demand SOCs and the crosswalk
INSERT INTO indemandcips (cip, cipcode, ciptitle)
SELECT DISTINCT cip2020code, crosswalk.cipcode, crosswalk.cip2020title
FROM soccipcrosswalk AS crosswalk
         JOIN indemandsocs AS demand
              ON crosswalk.soc2018code = demand."soc"
ORDER BY crosswalk.cipcode;