export const allLanguages = [
  "Arabic",
  "Chinese",
  "French",
  "French Creole",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Italian",
  "Japanese",
  "Korean",
  "Polish",
  "Portuguese",
  "Russian",
  "Spanish",
  "Tagalog",
  "Vietnamese",
];

export const dataValueToLanguage: { [key: string]: string } = {
  Arabic: "Arabic",
  Chinese: "Chinese",
  French: "French",
  "French/French Creole": "French Creole",
  German: "German",
  Greek: "Greek",
  "Yiddish/Hebrew": "Hebrew",
  "Indic/Hindu": "Hindi",
  Hungarian: "Hungarian",
  Italian: "Italian",
  Japanese: "Japanese",
  Korean: "Korean",
  Polish: "Polish",
  Portuguese: "Portuguese",
  Russian: "Russian",
  Spanish: "Spanish",
  "Tagalog (Philipines)": "Tagalog",
  Vietnamese: "Vietnamese",
};
