#!/usr/bin/env bash

cd $(git rev-parse --show-toplevel)

CSV_FILEPATH=$(pwd)/data/${CSV_FILENAME}

psql -U postgres -d "${DB_NAME}" -h localhost -p 5432 -c "\copy programs
    (PROVIDERID,
     OFFICIALNAME,
     CIPCODE,
     APPROVINGAGENCYID,
     OTHERAGENCY,
     SUBMITTEDTOWIB,
     TUITION,
     FEES,
     BOOKSMATERIALSCOST,
     SUPPLIESTOOLSCOST,
     OTHERCOSTS,
     TOTALCOST,
     PREREQUISITES,
     WIAELIGIBLE,
     LEADTODEGREE,
     DEGREEAWARDED,
     LEADTOLICENSE,
     LICENSEAWARDED,
     LEADTOINDUSTRYCREDENTIAL,
     INDUSTRYCREDENTIAL,
     FINANCIALAID,
     DESCRIPTION,
     CREDIT,
     TOTALCLOCKHOURS,
     CALENDARLENGTHID,
     FEATURESDESCRIPTION,
     WIBCOMMENT,
     STATECOMMENT,
     SUBMITTED,
     APPROVED,
     CONTACTNAME,
     CONTACTPHONE,
     PHONEEXTENSION,
     PROGRAMID,
     STATUSNAME)
    FROM '${CSV_FILEPATH}' WITH (FORMAT csv, DELIMITER ',', HEADER);"
