export const ExplorerPageStrings: Record<string, string> = {
  header: "Power up your search to find your next training opportunity",
  sectionOneHeader: "Get Started",
  sectionOneText:
    "The Training Explorer is a comprehensive listing of all schools and organizations offering education and job training programs that are eligible to receive publicly funded tuition assistance. To search for training, enter a training name, provider, or job title in the search bar below",
  sectionTwoHeader: "Funding",
  sectionTwoText:
    "Training with an in-demand label may be eligible for funding by New Jersey. NJ offers many options for training programs and funding through grants for those who qualify. To find out about your eligibility, get in touch with your local one-stop center.",
  sectionThreeHeader: "Resources for your training exploration",
  searchDescription: "Customize your search by occupation and geographic location",
  searchButton: "Search",
  fundingDescription: "New Jersey offers funding through grants for those who qualify",
  fundingButton: "Explore Funding",
  occupationDescription: "Find the fastest growing occupations in the state",
  occupationButton: "View Occupations",
  sectionFourHeader: "Learn how to use the Training Explorer from these commonly asked questions",
  enrollFaq: "I want to enroll in a training that I see on website",
  searchHelpFaq: "I don't know where to start my search and I need help with that",
  childCareFaq: "I need help with child care",
  fundingFaq: "I want to learn more about funding opportunities",
  jobListingsFaq: "I want to look at job listings",
  unemploymentInsuranceFaq: "I need help applying for unemployment insurance",
  healthInsuranceFaq: "I need help applying for health insurance",
  sectionFiveHeader: "Have More Questions?",
  getInTouchText: "Get in Touch",
  contactUsButtonText: "Contact Us",
};
