export const SearchAndFilterStrings: Record<string, string> = {
  searchButtonDefaultText: "Search",
  searchButtonUpdateResultsText: "Update Results",
  searchBarDefaultPlaceholderText: "Search for training courses",
  sortByLabel: "Sort by",
  sortByBestMatch: "Best Match",
  sortByCostLowToHigh: "Cost: Low to High",
  sortByCostHighToLow: "Cost: High to Low",
  sortByEmploymentRate: "Employment Rate",
  singularResultCountString: "{count} result",
  pluralResultCountString: "{count} results",
  mobileFilterText: "Edit Search or Filter",
  locationFilterLabel: "Miles from Zip Code",
  locationFilterMilesInputLabel: "Miles",
  locationFilterZipCodePlaceholder: "Zip Code",
  locationFilterZipCodeInvalid: "Please enter a 5-digit New Jersey ZIP code.",
  inDemandFilterLabel: "Show In-Demand Trainings Only",
  costFilterLabel: "Cost",
  maxCostLabel: "Max Cost",
  classFormatFilterLabel: "Class Format",
  classFormatInPersonLabel: "In-Person",
  classFormatOnlineLabel: "Online",
  timeToCompleteFilterLabel: "Time to Complete",
  timeToCompleteDaysLabel: "Days",
  timeToCompleteWeeksLabel: "Weeks",
  timeToCompleteMonthsLabel: "Months",
  timeToCompleteYearsLabel: "Years",
  clearAllFiltersButtonLabel: "Clear Filters",
  socCodeFilterLabel: "Filter by SOC Code",
  invalidSocCodeError: "Please enter a valid SOC code format, i.e. 43-9041.",
  cipCodeFilterLabel: "Filter by CIP Code",
  invalidCipCodeError: "Please enter a 6-digit CIP code.",
  countyFilterLabel: "Filter by County",
  programServicesFilterLabel: "Filter by Training Provider Services",
  eveningCoursesLabel: "Offers evening courses",
  wheelChairAccessibleLabel: "Wheelchair accessible",
  jobPlacementAssistLabel: "Job placement assistance",
  childcareAssistLabel: "Childcare assistance",
  languagesFilterLabel: "Filter by Languages",
  filterListExpandLabel: "Show more",
  filterListCollapseLabel: "Show less",
};
