export const SearchAndFilterStrings: Record<string, string> = {
  searchButtonDefaultText: "Search",
  searchButtonUpdateResultsText: "Update Results",
  searchBarDefaultPlaceholderText: "Search for training courses",
  sortByLabel: "Sort by",
  sortByBestMatch: "Best Match",
  sortByCostLowToHigh: "Cost: Low to High",
  sortByCostHighToLow: "Cost: High to Low",
  sortByEmploymentRate: "Employment Rate",
  singularResultCountString: "{count} result",
  pluralResultCountString: "{count} results",
  mobileFilterText: "Edit Search or Filter",
  locationFilterLabel: "Miles from Zip Code",
  locationFilterMilesInputLabel: "Miles",
  locationFilterZipCodePlaceholder: "Zip Code",
  locationFilterZipCodeInvalid: "Please enter a 5-digit New Jersey ZIP code.",
  inDemandFilterLabel: "Show In-Demand Trainings Only",
  costFilterLabel: "Cost",
  maxCostLabel: "Max Cost",
  classFormatFilterLabel: "Class Format",
  classFormatInPersonLabel: "In-Person",
  classFormatOnlineLabel: "Online",
  timeToCompleteFilterLabel: "Time to Complete",
  timeToCompleteDaysLabel: "Days",
  timeToCompleteWeeksLabel: "Weeks",
  timeToCompleteMonthsLabel: "Months",
  timeToCompleteYearsLabel: "Years",
};
