#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-Commit ✅"

# Initialize nvm and set the correct Node version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# Use nvm to get the correct path to npm
NPM_PATH=$(nvm which current | xargs dirname)/npm

# Check code formatting
npm run format || {
  echo 'Found code formatting issues that need to be fixed.'
  read -p "Press Enter to continue or Ctrl+C to cancel the commit" -n 1 -r
  echo    # move to a new line after user input
  exit 1
}

# Check ESLint standards
npm run lint || {
  echo 'Found linting issues that need to be fixed.'
  read -p "Press Enter to continue or Ctrl+C to cancel the commit" -n 1 -r
  echo    # move to a new line after user input
  exit 1
}

# Check tests
npm run test || {
  echo 'Found test issues that need to be fixed.'
  read -p "Press Enter to continue or Ctrl+C to cancel the commit" -n 1 -r
  echo    # move to a new line after user input
  exit 1
}

echo 'All checks passed! Committing now.'
